### ISSUE TITLE
Upstream OVN renamed "k8s.ovn.org/host-addresses" to "k8s.ovn.org/host-cidrs" 

### ISSUE THREAD

**Issue by rbbratta** [redhat-best-practices-for-k8s/certsuite#2121]
https://github.com/ovn-org/ovn-kubernetes/pull/3915

It looks like two files are affected.

https://github.com/test-network-function/cnf-certification-test/blob/main/cmd/certsuite/claim/compare/testdata/claim_observability.json#L249-L249

https://github.com/test-network-function/cnf-certification-test/blob/main/cmd/certsuite/claim/compare/testdata/claim_access_control.json#L250-L250

I don't know how to handle the changed based on versions.

**Comment by sebrandon1** [comment]
Thanks for the heads up!
